export const businessRegConstants = {
    SAVE_DATA: 'SAVE_BUSINESS_REG_DATA',
    GENERATE_REF: 'GENERATE_TRANSACTION_REF',
    BUSINESS_REG_REQUEST: 'BUSINESS_REG_REQUEST',
    BUSINESS_REG_SUCCESS: 'BUSINESS_REG_SUCCESS',
    BUSINESS_REG_FAILURE: 'BUSINESS_REG_FAILURE',

    BUSINESS_INDIVIDUAL_REG_REQUEST: 'BUSINESS_INDIVIDUAL_REG_REQUEST',
    BUSINESS_INDIVIDUAL_REG_SUCCESS: 'BUSINESS_INDIVIDUAL_REG_SUCCESS',
    BUSINESS_INDIVIDUAL_REG_FAILURE: 'BUSINESS_INDIVIDUAL_REG_FAILURE',

    NOB_REQUEST:'NATURES_OF_BUSINESS_REQUEST',
    NOB_SUCCESS:'NATURES_OF_BUSINESS_SUCCESS',
    NOB_FAILURE:'NATURES_OF_BUSINESS_FAILURE',
    
    UPDATE_TYPE:'UPDATE_BUSINESS_REG_TYPE'
};