export const companyRegConstants = {
    SAVE_DATA: 'SAVE_COMPANY_REG_DATA',
    GENERATE_REF: 'GENERATE_TRANSACTION_REF',
    COMPANY_REG_REQUEST: 'COMPANY_REG_REQUEST',
    COMPANY_REG_SUCCESS: 'COMPANY_REG_SUCCESS',
    COMPANY_REG_FAILURE: 'COMPANY_REG_FAILURE',

    COMPANY_INDIVIDUAL_REG_REQUEST: 'COMPANY_INDIVIDUAL_REG_REQUEST',
    COMPANY_INDIVIDUAL_REG_SUCCESS: 'COMPANY_INDIVIDUAL_REG_SUCCESS',
    COMPANY_INDIVIDUAL_REG_FAILURE: 'COMPANY_INDIVIDUAL_REG_FAILURE',

    BUSINESS_OBJ_REQUEST:'BUSINESS_OBJ_REQUEST',
    BUSINESS_OBJ_SUCCESS:'BUSINESS_OBJ_SUCCESS',
    BUSINESS_OBJ_FAILURE:'BUSINESS_OBJ_FAILURE',

    NOB_REQUEST:'NATURES_OF_BUSINESS_REQUEST',
    NOB_SUCCESS:'NATURES_OF_BUSINESS_SUCCESS',
    NOB_FAILURE:'NATURES_OF_BUSINESS_FAILURE',

    GET_ARTICLES_REQUEST:'GET_ARTICLES_REQUEST',
    GET_ARTICLES_SUCCESS:'GET_ARTICLES_SUCCESS',
    GET_ARTICLES_FAILURE:'GET_ARTICLES_FAILURE',

    UPDATE_TYPE:'UPDATE_COMPANY_REG_TYPE'
};