export const feedbackEmailConstants = {

    SEND_FEEDBACK_REQUEST: 'SEND_FEEDBACK_REQUEST',
    SEND_FEEDBACK_SUCCESS: 'SEND_FEEDBACK_SUCCESS',
    SEND_FEEDBACK_FAILURE: 'SEND_FEEDBACK_FAILURE',

};