export const locationConstants = {
 
    STATE_REQUEST: 'STATE_REQUEST',
    STATE_SUCCESS: 'STATE_SUCCESS',
    STATE_FAILURE: 'STATE_FAILURE',

    COUNTRY_REQUEST: 'COUNTRY_REQUEST',
    COUNTRY_SUCCESS: 'COUNTRY_SUCCESS',
    COUNTRY_FAILURE: 'COUNTRY_FAILURE',

    CITY_REQUEST: 'CITY_REQUEST',
    CITY_SUCCESS: 'CITY_SUCCESS',
    CITY_FAILURE: 'CITY_FAILURE',

};