export const reservationConstants = {
    SAVE_DATA: 'SAVE_RESERVATION_DATA',
    GENERATE_REF: 'GENERATE_TRANSACTION_REF',
    RESERVATION_REQUEST: 'NAME_RESERVATION_REQUEST',
    RESERVATION_SUCCESS: 'NAME_RESERVATION_SUCCESS',
    RESERVATION_FAILURE: 'NAME_RESERVATION_FAILURE',

    UPDATE_TYPE:'UPDATE_RESERVATION_TYPE',
    UPDATE_COMPANY_TYPE:'UPDATE_COMPANY_TYPE'
};