export const serviceConstants = {
    GENERATE_REF: 'GENERATE_TRANSACTION_REF',

    GET_SERVICES_REQUEST:'GET_USER_SERVICES_REQUEST',
    GET_SERVICES_FAILURE:'GET_USER_SERVICES_FAILURE',
    GET_SERVICES_SUCCESS:'GET_USER_SERVICES_SUCCESS',

    UPDATE_SERVICE_PAYMENT:'UPDATE_SERVICE_PAYMENT'
}; 