export const taskConstants = {

    SILENTLY_GET_TASKS_REQUEST:'SILENTLY_GET_USER_TASKS_REQUEST',
    SILENTLY_GET_TASKS_FAILURE:'SILENTLY_GET_USER_TASKS_FAILURE',
    SILENTLY_GET_TASKS_SUCCESS:'SILENTLY_GET_USER_TASKS_SUCCESS',

    GET_TASKS_REQUEST:'GET_USER_TASKS_REQUEST',
    GET_TASKS_FAILURE:'GET_USER_TASKS_FAILURE',
    GET_TASKS_SUCCESS:'GET_USER_TASKS_SUCCESS',

    GET_TASK_FILES_REQUEST:'GET_USER_TASK_FILES_REQUEST',
    GET_TASK_FILES_FAILURE:'GET_USER_TASK_FILES_FAILURE',
    GET_TASK_FILES_SUCCESS:'GET_USER_TASK_FILES_SUCCESS',

    LOAD_MORE_TASKS_REQUEST:'LOAD_MORE_USER_TASKS_REQUEST',
    LOAD_MORE_TASKS_FAILURE:'LOAD_MORE_USER_TASKS_FAILURE',
    LOAD_MORE_TASKS_SUCCESS:'LOAD_MORE_USER_TASKS_SUCCESS',

    MARK_AS_VIEWED_REQUEST:'MARK_AS_VIEWED_REQUEST',
    MARK_AS_VIEWED_FAILURE:'MARK_AS_VIEWED_FAILURE',
    MARK_AS_VIEWED_SUCCESS:'MARK_AS_VIEWED_SUCCESS',

    SAVE_FILE_PATHS: 'SAVE_TASK_FILES_PATHS',
    UPDATE_CATEGORY:'UPDATE_CATEGORY'

};